### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by InterLinked1** [mmalcek/basicToOauth#1]
Since the README says "on request", would you mind adding some Linux instructions and perhaps a binary as well?

I would compile it myself if this were in C, but I'm not sure what the steps would be for go.

I am trying to get a server module to subscribe to an Exchange online calendar, and the ICS feed doesn't contain reminder details, so I'd like to see if I can get EWS working. So far no luck, probably because of the basic authentication. Second to Microsoft not being a PITA, this is just what we need.

**Comment by mmalcek** [comment]
Hi, Once you have golang installed on your favourite platform
https://go.dev/doc/install
build is as easy as run "go build" command inside project folder

Even cross compilation is pretty straight forward 
https://freshman.tech/snippets/go/cross-compile-go-programs/

I've added linux build for you ;)
https://github.com/mmalcek/basicToOauth/releases
params: ./basicToOauth -service (install,start,stop,uninstall) should work on linux as well

btw: If you are starting fresh new project it might be better start wit GRAPH API ;)
https://learn.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&preserve-view=true

**Comment by InterLinked1** [comment]
Thanks, looks very nice!

I just get a blank page when I go to: https://login.microsoftonline.com/common/oauth2/nativeclient

Do you know how the instructions differ for non-Azure/O365 tenant accounts? I am trying to set it up for a regular consumer Microsoft account, though  I believe the same protocols are available to those as to business customers (Exchange, etc.). All the Azure tenant stuff though doesn't apply as far as I can tell.
