### ISSUE TITLE
not working with outlook

### ISSUE THREAD

**Issue by CloudHoang** [mmalcek/basicToOauth#2]
I'm trying config it working with pop3/imap on outlook desktop but no luck.
Noted: Port changed to 80
![image](https://user-images.githubusercontent.com/36913879/191168263-def1557a-ebb6-4e65-931c-ceee0b217d95.png)

**Comment by mmalcek** [comment]
Hi, this application is intended for HTTP protocol only (not SMTP, POP3 or IMAP). I've just updated readme to make it more obvious. 
Anyway I think in outlook under "More Settings" is an option - something like "use Outlook Web Access" which I think can work with basicToOauth tool (not tested).
