### ISSUE TITLE
How to do multiple Tenants

### ISSUE THREAD

**Issue by SWEIT-SDK** [mmalcek/basicToOauth#6]
Hi, 

is there a way you can assign multiple tenants to this? Our tool connected to multiple tenants throug the default https://outlook.office365.com and now, with basictooauth2 only one tenant is configured in config.yaml so we are only capable of using our tool with 1 tenant.

**Comment by mmalcek** [comment]
This sounds like pretty specific use case - user accounts are under Tenant. 
I'm not going to modify this repo but we can discuss this further - if you explain me the workflow I can create specific version for you. Of course as paid task.
If you are interested drop me an E-mail - mmalcek@gmail.com
